aliases:
  "Agawam": "Agawam 12U"
  "Granby": "Granby 12U"
  "Newington": "Newington 12U"
  "RHAM": "RHAM 12U"
  "Vernon": "Vernon 12U"
  "West Springfield": "West Springfield 12U"
  "South Hadley": "South Hadley 12U"