aliases:
  "Agawam": "Agawam 12U"
  "Berkshires": "Berkshire"
  "Granby": "Granby 12U"
  "Minnechaug": "Minnechaug 12U"
  "Newington": "Newington 12U"
  "RHAM": "RHAM 12U"
  "Somers Red": "Somers 12U Red"
  "Vernon": "Vernon 12U"
  "West Springfield": "West Springfield 12U"
  "South Hadley": "South Hadley 12U"
